name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        name: davidbohl/user-service-sites
        tag: $(date +%s)
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
